### PR TITLE
Added new `check`, `read`, and `remove` modules

### PR DESCRIPTION
**Pull request by frol**

### CODE REVIEW

**Comment by frol** [comment]
I am working on tests at the moment, but decided to share the implementation for review.

**Comment by frol** [comment]
Should I use `try!` instead of `?` operator? Do you target Rust <1.13?

**Comment by Byron** [comment]
I will try to have a look tomorrow.
Also I think it’s fair to target the current edition of Rust, where ‘?’ is
standard.

**Comment by frol** [comment]
I have updated the PR with tests and one more util (`check::is_folder_empty`).

**Comment by frol** [comment]
@Byron I am kindly reminding you about PRs :)

**Comment by Byron** [comment]
Sorry for the long wait, and thanks a lot for taking the time to contribute!
I am merging this PR now, make you a collaborator, and add you as an owner of the crate so you can publish new versions yourself.

**Comment by Byron** [comment]
@frol I tried to be smart and find one of your Rust repositories, to figure out your crates.io user that way. Maybe you could login and provide it to me? Benefit would be that you can publish this crate all by yourself.
Thanks and cheers

**Comment by frol** [comment]
@Byron I have no published Rust crates yet. I have just signed up on Crates.io with my GitHub account.  Here is my info: `"Vladyslav Frolov <frolvlad@gmail.com>"` (I am not sure what kind of handle is needed to add another user to the list of maintainers, so let me know if you need anything else)

**Comment by Byron** [comment]
screen shot 2018-05-09 at 18 03 49

Great, I think that worked! Please feel free to cut a new release.

**Comment by frol** [comment]
@Byron Yay! I used [cargo-release](https://github.com/sunng87/cargo-release) and everything went perfectly smooth:

```
$ cargo release --tag-prefix=v minor
```

**Comment by frol** [comment]
Well, except the documentation. I am figuring how to upload the docs now.

**Comment by Byron** [comment]
Great to hear! If the doc urls aren’t yet pointing to docs.rs, I think they
should.
This crate is rather old and definitely pre-docs.rs :D

**Comment by frol** [comment]
The link seems to be right. Does it build the documentation automatically? It just still shows only 1.0.0 release there: https://docs.rs/crate/fs-utils/

**Comment by frol** [comment]
Yeah, it should build the docs automatically, but there is [a backlog of other releases in the queue](https://docs.rs/releases/queue), so we should just wait, I believe.

**Comment by Byron** [comment]
Thanks so much for taking the time to get in touch and preventing yet another but similar crate to be published :)!
That said, if you need anything, just let me know. 
Please consider this _your_ crate, you can proceed as you like but I will be there to bounce back some thoughts if you seek them. When the time comes and you would like to see put this repository under your own name, I am happy to transfer ownership, too.

Cheers,
Sebastian

**Pull request merged**
